<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Identity\SmartSchool.Modules.Identity.Infrastructure\SmartSchool.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\Modules\Identity\SmartSchool.Modules.Identity.Presentation\SmartSchool.Modules.Identity.Presentation.csproj" />
    <ProjectReference Include="..\..\..\..\src\SmartSchool.Api\SmartSchool.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
