<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Identity\SmartSchool.Modules.Identity.Domain\SmartSchool.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\SmartSchool.Modules.Identity.Application\SmartSchool.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\SmartSchool.Modules.Identity.Infrastructure\SmartSchool.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\SmartSchool.Modules.Identity.Presentation\SmartSchool.Modules.Identity.Presentation.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\SmartSchool.SharedKernel\SmartSchool.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\SmartSchool.Application.Abstractions\SmartSchool.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\SmartSchool.Infrastructure\SmartSchool.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\SmartSchool.EventBus\SmartSchool.EventBus.csproj" />
  </ItemGroup>

</Project>
